nevermind998/uks

.dockerignore
docker-compose.yaml
uks_front/Dockerfile
uks_project/Dockerfile
uks_project/uks_project/settings.py
uks_project/wait-for-it.sh

closes: https://github.com/nevermind998/uks/issues/14
Creating docker files that will support the backend, front end, and database of application.

Creating docker files and docker-compose file

---

uks_project/user_actions_management_app/admin.py
uks_project/user_actions_management_app/serializers.py
uks_project/user_actions_management_app/urls.py
uks_project/user_actions_management_app/views.py

feat: api for comments handling added

---

uks_project/user_actions_management_app/models.py
uks_project/user_actions_management_app/serializers.py
uks_project/user_actions_management_app/urls.py
uks_project/user_actions_management_app/views.py

feat: api for reactions created

---

uks_project/project_management_app/serializers.py
uks_project/project_management_app/urls.py
uks_project/project_management_app/views.py

feat: CRUD for milestone

---

uks_project/project_management_app/serializers.py
uks_project/project_management_app/urls.py
uks_project/project_management_app/views.py

feat: CRUD for label

---

uks_project/user_actions_management_app/management/set_up_database.py
uks_project/user_actions_management_app/tests.py
uks_project/user_actions_management_app/tests/test_model.py
uks_project/user_actions_management_app/tests/test_user_actions.py

feat: comments api tests added

---

uks_project/user_actions_management_app/management/set_up_database.py
uks_project/user_actions_management_app/tests/test_model.py
uks_project/user_actions_management_app/tests/test_user_actions.py

feat: reactions api tests added

---

uks_project/user_actions_management_app/management/set_up_database.py
uks_project/user_actions_management_app/tests/test_model.py
uks_project/user_actions_management_app/tests/test_repo_actions.py

feat: tests for repo actions api added

---

uks_front/src/App.tsx
uks_front/src/Store/slices/example.slice.ts
uks_front/src/Style/components/_create-repo.scss
uks_front/src/Style/components/_dashboard.scss
uks_front/src/Style/components/_sign-up.scss
uks_front/src/Style/main.scss
uks_front/src/Types/repository.types.ts
uks_front/src/Views/CreateRepository/createRepositorySchema.ts
uks_front/src/Views/CreateRepository/index.tsx
uks_front/src/Views/Dashboard/index.tsx
uks_front/src/Views/ProjectManagement/MilestoneForm/index.tsx
uks_front/src/api/apiBase.ts
uks_front/src/api/repositories.ts
uks_front/src/index.tsx
uks_project/versioning_management_app/models.py
uks_project/versioning_management_app/serializers.py
uks_project/versioning_management_app/tests/test_versioning_app.py
uks_project/versioning_management_app/views.py

feat: add form for new repository

---

uks_front/package-lock.json
uks_front/package.json
uks_front/src/App.tsx
uks_front/src/Style/components/_repository-display.scss
uks_front/src/Style/main.scss
uks_front/src/Types/action.types.ts
uks_front/src/Views/ProjectManagement/MilestoneForm/index.tsx
uks_front/src/Views/RepositoryDisplay/AboutRepository/index.tsx
uks_front/src/Views/RepositoryDisplay/Forks/index.tsx
uks_front/src/Views/RepositoryDisplay/Stargazers/index.tsx
uks_front/src/Views/RepositoryDisplay/Watchers/index.tsx
uks_front/src/Views/RepositoryDisplay/index.tsx
uks_front/src/api/repositories.ts
uks_project/uks_project/settings.py
uks_project/user_actions_management_app/tests/test_repo_actions.py
uks_project/user_actions_management_app/tests/test_user_actions.py
uks_project/user_actions_management_app/views.py
uks_project/versioning_management_app/views.py

feat: repository display created

---

uks_front/src/App.tsx
uks_front/src/Style/components/_modal-dialog-form.scss
uks_front/src/Style/main.scss
uks_front/src/Types/branch.types.ts
uks_front/src/Views/Branch/branchValidationSchema.ts
uks_front/src/Views/Branch/index.tsx
uks_front/src/Views/RepositoryDisplay/AboutRepository/index.tsx
uks_front/src/api/branches.ts
uks_project/uks_project/settings.py
uks_project/versioning_management_app/models.py
uks_project/versioning_management_app/tests/test_versioning_branch.py

feat: create form for new branches

---

uks_project/project_management_app/tests/test_user_action.py
uks_project/project_management_app/views.py
uks_project/uks_project/settings.py
uks_project/users_management_app/views.py
uks_project/versioning_management_app/views.py

fix: remove 404 errors

---

uks_front/src/Style/components/_repository-display.scss
uks_front/src/Types/action.types.ts
uks_front/src/Views/RepositoryDisplay/AboutRepository/index.tsx
uks_front/src/Views/RepositoryDisplay/CreateFork/index.tsx
uks_front/src/Views/RepositoryDisplay/Forks/index.tsx
uks_front/src/Views/RepositoryDisplay/Stargazers/index.tsx
uks_front/src/Views/RepositoryDisplay/Watchers/index.tsx
uks_front/src/Views/RepositoryDisplay/index.tsx
uks_front/src/api/repositories.ts
uks_project/uks_project/settings.py

feat: implement actions on frontend

---

uks_front/src/Types/action.types.ts
uks_front/src/Views/CommentsDisplay/Comment/index.tsx
uks_front/src/Views/CommentsDisplay/index.tsx
uks_front/src/Views/RepositoryDisplay/index.tsx
uks_front/src/api/comments.ts

feat: component for displaying comments added

---

uks_front/src/Views/RepositoryDisplay/PullRequestDisplay/DisplaySelectedPR/index.tsx
uks_front/src/Views/RepositoryDisplay/PullRequestDisplay/index.tsx
uks_project/uks_project/settings.py

fix: replace button when status change

---

uks_front/src/Style/components/_repository-display.scss
uks_front/src/Types/repository.types.ts
uks_front/src/Views/CommentsDisplay/Comment/index.tsx
uks_front/src/Views/CommentsDisplay/CommentReactions/index.tsx
uks_front/src/Views/CommentsDisplay/index.tsx
uks_front/src/Views/RepositoryDisplay/AboutRepository/index.tsx
uks_front/src/Views/RepositoryDisplay/PullRequestDisplay/DisplaySelectedPR/index.tsx
uks_front/src/Views/RepositoryDisplay/index.tsx
uks_front/src/api/projectManagement.ts
uks_project/uks_project/settings.py
uks_project/versioning_management_app/serializers.py

fix: repo actions fixed

---

uks_front/src/Views/CommentsDisplay/Comment/index.tsx
uks_front/src/Views/CommentsDisplay/index.tsx
uks_front/src/Views/RepositoryDisplay/PullRequestDisplay/DisplaySelectedPR/index.tsx
uks_front/src/api/projectManagement.ts

feat: pr review implemented

---

.github/workflows/deploy.yml
.github/workflows/tag.yml

feat: merge on main action

---

uks_front/package-lock.json
uks_front/package.json
uks_front/src/Style/components/_repository-display.scss
uks_front/src/Types/commit.types.ts
uks_front/src/Types/issue.types.ts
uks_front/src/Views/Insights/CommitsTab/index.tsx
uks_front/src/Views/Insights/Contributors/index.tsx
uks_front/src/Views/Insights/Pulse/index.tsx
uks_front/src/Views/Insights/index.tsx
uks_front/src/Views/ProjectManagmentDisplay/IssueDisplay/DisplaySelectedIssue/index.tsx
uks_front/src/Views/RepositoryDisplay/index.tsx
uks_front/src/api/commits.ts
uks_project/project_management_app/views.py
uks_project/versioning_management_app/urls.py
uks_project/versioning_management_app/views.py

feat: insights

---

uks_front/src/App.tsx
uks_front/src/Components/Layout/index.tsx
uks_front/src/Style/components/_dashboard.scss
uks_front/src/Views/CreateRepository/index.tsx
uks_front/src/Views/Dashboard/index.tsx
uks_front/src/Views/ProfileEdit/index.tsx
uks_front/src/Views/RepositoryDisplay/index.tsx
uks_front/src/Views/SignIn/index.tsx
uks_front/src/api/userAuthentication.ts
uks_project/users_management_app/urls.py
uks_project/users_management_app/views.py
uks_project/versioning_management_app/permissions.py

fix: enable profile editing
